package com.minjem.dumi.response

import com.minjem.dumi.model.MasukData

data class MasukResponse(
    val `data`: List<Data>,
    val message: String,
    val status: Boolean
)

data class Data(
    val agama: Any,
    val alamat: Any,
    val bank: String,
    val desa: Any,
    val email: Any,
    val gajiPokok: Any,
    val golongan: Any,
    val hubungan: Any,
    val ibuKandung: Any,
    val id: Int,
    val inskerNama: Any,
    val jenis_kelamin: Any,
    val kabkota: Any,
    val kampung: Any,
    val kartu_kredit: Any,
    val kecamatan: Any,
    val kelurahan: Any,
    val ket_title: Any,
    val kodepos: Any,
    val mkBulan: Any,
    val mkTahun: Any,
    val namaDarurat: Any,
    val namaInput: Any,
    val namaJabatan: Any,
    val namaPasangan: Any,
    val namaPns: String,
    val namaRekening: String,
    val nama_penanggung: Any,
    val nipBaru: String,
    val noHpDarurat: Any,
    val noKtpPasangan: Any,
    val no_hp: Any,
    val no_ktp_penanggung: Any,
    val noktp: Any,
    val noktp1: Any,
    val norek: String,
    val npwpNomor: Any,
    val pendidikan: Any,
    val photo_ktp: String,
    val photo_profile: String,
    val photo_selfi: String,
    val provinsi: Any,
    val rt: Any,
    val rw: Any,
    val saldo: Int,
    val saldo_max: Int,
    val sandi: String,
    val skor: Any,
    val statusPNS: Any,
    val status_hubungan: Any,
    val status_kawin: Any,
    val status_rumah: Any,
    val status_topup: Int,
    val tanggungan: Any,
    val tempatLahir: Any,
    val tglLhrPns: Any,
    val tglRegister: String,
    val tmtCpns: Any,
    val tmtPensiun: Any,
    val token: Any
)